# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Andy"
tagline: ""
description: "Follow <a href=\"https://micro.blog/andyb\">@andyb on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/andyb\">@andyb on Micro.blog</a>."
baseurl: ""
url: "https://andyb.micro.blog"
markdown: "kramdown"
username: "andyb"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Andy"
name: "Andy"
gravatar_hash: "afeeaeaa727cd52ccb14d1231a30c5e0"
avatar: "https://micro.blog/andyb/avatar.jpg"
full_name: "Andy"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "3559"